// Code generated by candi v1.17.16.

package shared

// Environment additional in this service
type Environment struct {
	// more additional environment with struct tag is environment key example:
	// ExampleHost string `env:"EXAMPLE_HOST"`
	AnonymousTokenKey string `env:"JWT_ANONYMOUS_TOKEN_SECRET_KEY"`
	AccessTokenKey    string `env:"JWT_ACCESS_TOKEN_SECRET_KEY"`
	RefreshTokenKey   string `env:"JWT_REFRESH_TOKEN_SECRET_KEY"`
}

var sharedEnv Environment

// GetEnv get global additional environment
func GetEnv() Environment {
	return sharedEnv
}

// SetEnv get global additional environment
func SetEnv(env Environment) {
	sharedEnv = env
}
