// Code generated by candi v1.17.16.

package repository

import (
	"context"

	"go-api-service-with-candi/internal/modules/auth/domain"
	shareddomain "go-api-service-with-candi/pkg/shared/domain"

	"github.com/golangid/candi/candishared"
)

// AuthRepository abstract interface
type AuthRepository interface {
	FetchAll(ctx context.Context, filter *domain.FilterAuth) ([]shareddomain.Auth, error)
	Count(ctx context.Context, filter *domain.FilterAuth) int
	Find(ctx context.Context, filter *domain.FilterAuth) (shareddomain.User, error)
	Save(ctx context.Context, data *shareddomain.User, updateOptions ...candishared.DBUpdateOptionFunc) error
	Delete(ctx context.Context, filter *domain.FilterAuth) (err error)
}
